name: native_barcode_scanner
description: Fast barcode/QR scanner plugin using PlatformView and processing on native side
version: 1.0.6
repository: https://github.com/freedelity/flutter_native_barcode_scanner

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: be.freedelity.barcode_scanner
        pluginClass: BarcodeScannerPlugin
      ios:
        pluginClass: BarcodeScannerPlugin
